---
abstract: 'interact with a t/test_manifest file'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  File::Temp: '0'
  Test::More: '1'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::Spec::Functions: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Manifest
no_index:
  directory:
    - t
    - inc
requires:
  File::Spec: '0'
  File::Spec::Functions: '0'
  Test::Harness: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/briandfoy/test-manifest/issues
  homepage: https://github.com/briandfoy/test-manifest
  repository: https://github.com/briandfoy/test-manifest.git
version: '2.022'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
